export const ADD_SPLASH_IMAGE = "ADD_SPLASH_IMAGE";
export const RESET_GLOBAL_STATE = "RESET_GLOBAL_STATE";
export const GET_SPLASH_IMAGE = "GET_SPLASH_IMAGE";


//Premvati Listing
export const ADD_PREMVATI = "ADD_PREMVATI";
export const GET_PREMVATI = "GET_PREMVATI";

//Master Management
export const ADD_PRAVRUTI = "ADD_PRAVRUTI";
export const GET_PRAVRUTI = "GET_PRAVRUTI";
export const UPDATE_PRAVRUTI = "UPDATE_PRAVRUTI";
export const DELETE_PRAVRUTI = "DELETE_PRAVRUTI";
export const ADD_KSHETRA = "ADD_KSHETRA";
export const UPDATE_KSHETRA = "UPDATE_KASHETRA";
export const GET_KSHETRA = "GET_KSHETRA";
export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const GET_DESIGNATION = "GET_DESIGNATION";
export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";

//User Master
export const ADD_USER = "ADD_USER";
export const GET_USER = "GET_USER";

//Product Master
export const GET_FOOD_CATEGORY = "GET_FOOD_CATEGORY";
export const GET_FOOD_ITEM = "GET_FOOD_ITEM";
export const ADD_FOOD_CATEGORY = "ADD_FOOD_CATEGORY";
export const ADD_FOOD_ITEM = "ADD_FOOD_ITEM";
export const GET_SERVING_CATEGORY = "GET_SERVING_CATEGORY";
export const ADD_SERVING_CATEGORY = "ADD_SERVING_CATEGORY";
export const GET_SERVING_METHOD = "GET_SERVING_METHOD";
export const ADD_SERVING_METHOD = "ADD_SERVING_METHOD";
export const GET_PRE_PACKAGE_FOOD_CATEGORY = "GET_PRE_PACKAGE_FOOD_CATEGORY";
export const GET_PRE_PACKAGE_FOOD_ITEM = "GET_PRE_PACKAGE_FOOD_ITEM";
export const ADD_PRE_PACKAGE_FOOD_CATEGORY = "ADD_PRE_PACKAGE_FOOD_CATEGORY";
export const ADD_PRE_PACKAGE_FOOD_ITEM = "ADD_PRE_PACKAGE_FOOD_ITEM";


//Order Listing
export const GET_UNPAID_ORDER_LIST = "GET_UNPAID_ORDER_LIST";
export const GET_PAID_ORDER_LIST = "GET_PAID_ORDER_LIST";
export const GET_PRE_PACKAGE_PAID_ORDER_LIST = "GET_PRE_PACKAGE_PAID_ORDER_LIST";
export const GET_PRE_PACKAGE_UNPAID_ORDER_LIST = "GET_PRE_PACKAGE_UNPAID_ORDER_LIST";
export const GET_PAYMENT = "GET_PAYMENT";
export const GET_PRE_PACKAGE_PAYMENT = "GET_PRE_PACKAGE_PAYMENT";



