export const ADD_SPLASH_IMAGE = "ADD_SPLASH_IMAGE";
export const RESET_GLOBAL_STATE = "RESET_GLOBAL_STATE";
export const GET_SPLASH_IMAGE = "GET_SPLASH_IMAGE";

export const LOGIN_ADMIN = "LOGIN_ADMIN"
//Premvati Listing
export const ADD_PREMVATI = "ADD_PREMVATI";
export const GET_PREMVATI = "GET_PREMVATI";
export const UPDATE_PREMVATI = "UPDATE_PREMVATI";
export const DELETE_PREMVATI = "DELETE_PREMVATI";

//Master Management
export const ADD_PRAVRUTI = "ADD_PRAVRUTI";
export const GET_PRAVRUTI = "GET_PRAVRUTI";
export const UPDATE_PRAVRUTI = "UPDATE_PRAVRUTI";
export const DELETE_PRAVRUTI = "DELETE_PRAVRUTI";
export const DELETE_KSHETRA = "DELETE_KSHETRA";
export const DELETE_DESIGNATION = "DELETE_DESIGNATION";
export const ADD_KSHETRA = "ADD_KSHETRA";
export const UPDATE_KSHETRA = "UPDATE_KASHETRA";
export const GET_KSHETRA = "GET_KSHETRA";
export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const GET_DESIGNATION = "GET_DESIGNATION";
export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";

//User Master
export const ADD_USER = "ADD_USER";
export const GET_ADMIN_USER = "GET_ADMIN_USER"
export const ADD_ADMIN_USER = "ADD_ADMIN_USER"
export const EDIT_ADMIN_USER = "EDIT_ADMIN_USER"
export const DELETE_ADMIN_USER = "DELETE_ADMIN_USER"
export const GET_USER = "GET_USER";
export const DELETE_USER = "DELETE_USER"
export const UPDATE_USER = "UPDATE_USER"

//Product Master
export const GET_FOOD_CATEGORY = "GET_FOOD_CATEGORY";
export const GET_FOOD_ITEM = "GET_FOOD_ITEM";
export const ADD_FOOD_CATEGORY = "ADD_FOOD_CATEGORY";
export const ADD_FOOD_ITEM = "ADD_FOOD_ITEM";
export const GET_SERVING_CATEGORY = "GET_SERVING_CATEGORY";
export const ADD_SERVING_CATEGORY = "ADD_SERVING_CATEGORY";
export const GET_SERVING_METHOD = "GET_SERVING_METHOD";
export const ADD_SERVING_METHOD = "ADD_SERVING_METHOD";
export const GET_PRE_PACKAGE_FOOD_CATEGORY = "GET_PRE_PACKAGE_FOOD_CATEGORY";
export const GET_PRE_PACKAGE_FOOD_ITEM = "GET_PRE_PACKAGE_FOOD_ITEM";
export const ADD_PRE_PACKAGE_FOOD_CATEGORY = "ADD_PRE_PACKAGE_FOOD_CATEGORY";
export const ADD_PRE_PACKAGE_FOOD_ITEM = "ADD_PRE_PACKAGE_FOOD_ITEM";
export const GET_BULK_ORDER_CATEGORY = "GET_BULK_ORDER_CATEGORY";
export const ADD_BULK_ORDER_CATEGORY = "ADD_BULK_ORDER_CATEGORY";
export const GET_BULK_ORDER_ITEM = "GET_BULK_ORDER_ITEM";
export const ADD_BULK_ORDER_ITEM = "ADD_BULK_ORDER_ITEM";
export const ADD_ITEM = "ADD_ITEM";
export const GET_ITEM = "GET_ITEM";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";

//Order Listing
export const GET_UNPAID_ORDER_LIST = "GET_UNPAID_ORDER_LIST";
export const GET_PAID_ORDER_LIST = "GET_PAID_ORDER_LIST";
export const GET_PENDING_ORDER_LIST = "GET_PENDING_ORDER_LIST";
export const GET_PRE_PACKAGE_PAID_ORDER_LIST = "GET_PRE_PACKAGE_PAID_ORDER_LIST";
export const GET_PRE_PACKAGE_UNPAID_ORDER_LIST = "GET_PRE_PACKAGE_UNPAID_ORDER_LIST";
export const GET_PRE_PACKAGE_PENDING_ORDER_LIST = "GET_PRE_PACKAGE_PENDING_ORDER_LIST";
export const GET_PAYMENT = "GET_PAYMENT";
export const GET_PRE_PACKAGE_PAYMENT = "GET_PRE_PACKAGE_PAYMENT";
export const GET_PAID_ORDER = "GET_PAID_ORDER";
export const GET_PENDING_ORDER = "GET_PENDING_ORDER";
export const GET_PRE_PAID_ORDER = "GET_PRE_PAID_ORDER";
export const GET_PRE_PENDING_ORDER = "GET_PRE_PENDING_ORDER";
export const GET_CANCEL_ORDER = "GET_CANCEL_ORDER";
export const GET_PRE_CANCEL_ORDER = "GET_PRE_CANCEL_ORDER";
export const GET_PAID_BULK_ORDER = "GET_PAID_BULK_ORDER";
export const GET_BULK_CANCEL_ORDER = "GET_BULK_CANCEL_ORDER";
export const GET_PAID_BULK_ORDER_LIST = "GET_PAID_BULK_ORDER_LIST";
export const GET_PENDING_BULK_ORDER_LIST = "GET_PENDING_BULK_ORDER_LIST";
export const GET_UNPAID_BULK_ORDER_LIST = "GET_UNPAID_BULK_ORDER_LIST";
export const ACCEPT_BULK_ORDER = "ACCEPT_BULK_ORDER";



